# Generated by Django 3.2.8 on 2021-10-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonprofile',
            old_name='userUIDToken',
            new_name='uidToken',
        ),
    ]
