# Generated by Django 3.2.8 on 2021-10-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_useruidtoken_anonprofile_uidtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAPISim',
            fields=[
                ('transactionNo', models.CharField(max_length=12, unique=True)),
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('uidToken', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='messageHeading',
            new_name='messageTitle',
        ),
        migrations.AlterField(
            model_name='anonprofile',
            name='deviceID',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='anonprofile',
            name='shareableCode',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('init', 'Initiated by requester'), ('accepted', 'Lender ready to share'), ('rejected', 'Lender rejects request'), ('shared', 'ekyc shared with requester'), ('commited', 'Address updated successfully'), ('aborted', 'Aborted due to any reason')], default='init', max_length=10),
        ),
    ]
