# Generated by Django 3.2.8 on 2021-10-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_offlineekyc'),
        ('core', '0004_transaction_transactionno'),
    ]

    operations = [
    ]
