# Generated by Django 3.2.8 on 2021-10-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0004_offlineekyc_0004_transaction_transactionno'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedAddress',
            fields=[
                ('transactionID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=12)),
                ('co', models.CharField(max_length=1024)),
                ('house', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('lm', models.CharField(max_length=256)),
                ('lo', models.CharField(max_length=256)),
                ('vtc', models.CharField(max_length=256)),
                ('subdist', models.CharField(max_length=256)),
                ('dist', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('pc', models.IntegerField()),
                ('po', models.CharField(max_length=512)),
            ],
        ),
        migrations.RenameField(
            model_name='offlineekyc',
            old_name='transactionId',
            new_name='transactionID',
        ),
        migrations.RenameField(
            model_name='otpapisim',
            old_name='transactionNo',
            new_name='transactionID',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionNo',
            new_name='transactionID',
        ),
    ]
