# Generated by Django 3.2.8 on 2021-10-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211029_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatedaddress',
            name='lo',
        ),
        migrations.AddField(
            model_name='updatedaddress',
            name='loc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='updatedaddress',
            name='co',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='updatedaddress',
            name='house',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='updatedaddress',
            name='lm',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='updatedaddress',
            name='po',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='updatedaddress',
            name='street',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
