# Generated by Django 3.2.8 on 2021-10-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211029_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('init', 'Initiated by requester'), ('accepted', 'Lender ready to share'), ('rejected', 'Lender rejects request'), ('shared', 'ekyc shared with requester'), ('commited', 'Address updated successfully'), ('aborted', 'Aborted due to any reason'), ('withdrawn', 'Requester Withdrew the request')], default='init', max_length=10),
        ),
    ]
