# Generated by Django 3.2.8 on 2021-10-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_transaction_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='OTPAPISim',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
